### ISSUE TITLE
Cannot paste into registration's personal code field

### ISSUE THREAD

**Issue by gedrox** [Ameriks/velo.lv#2]
Paste doesn't work due to input's max length 12 limit and "mask" plugin. Most sane solution is to disable the "mask" plugin leaving only validation. Simplest is to remove the maxlength attribute or increasing it to 24.

Also can't fill this field on Android phone using Chrome browser.

**Comment by Ameriks** [comment]
Yes, I don't like how SSN masking works. Masking should be removed and we need to leave validation to .change() event. Server validation is already in place, so only GUI updates are required.
