### ISSUE TITLE
Previous / Next buttons missing in mobile version

### ISSUE THREAD

**Issue by Tardymo** [Ameriks/velo.lv#7]
In mobile version it is not possible to get past first 100 records in Participants list and Results, because "Next" button is missing at the bottom of list.

**Comment by Ameriks** [comment]
I see that there is wrong media query that hides buttons in case if width is smaller than 390px. Fix is on the way.

**Comment by Ameriks** [comment]
Thanks. Issue fixed. There could still be cached version without button, but it will be automatically replaced with fixed version shortly.
